### ISSUE TITLE
Please update class location data for the current semester

### ISSUE THREAD

**Issue by unforgettableid** [isaackogan/YorkUClassFinder#3]
Hi!

When I pull down the "School Session" drop-down menu at https://find.yorku.dev/, it looks like the current term (S2) and the upcoming term (Fall/Winter) aren't listed yet.  I think all I see are three sessions from the past.

I wonder if you could please delete all the past semesters, and add the current and future semesters, and then possibly make a Reddit /r/yorku post telling the world that you've done so?

Thank you for reading this, and thank you for creating this useful tool!

**Comment by isaackogan** [comment]
Hi, I'm in somewhat of a predicament in this regard as I am now employed at York. I'd like to release an official tool with this functionality through proper channels. That said I don't know if that will be doable before September, because im busy. At the same time, it could be up to 3h of work to update this scraped version to the new term 🧐

We'll see what I think of

**Comment by isaackogan** [comment]
Updated for 2023.

P.S. It was, indeed, 3 hours of work.

**Comment by unforgettableid** [comment]
> Updated for 2023.

Excellent!  Thank you very much.

> I'd like to release an official tool with this functionality through proper channels.

Your tool is already written.  If you'd have to rewrite it again, that would be a waste.

On the other hand, if you could move the already-existing code to a York-hosted server, so that the tool will (hopefully) still be maintained even after you graduate, that might be very worthwhile.

Also, if the code is hosted by York, maybe someone could then add "Directions" links to the [schedule plotter](https://w2prod.sis.yorku.ca/Apps/WebObjects/cdm.woa/wa/DirectAction/cds) and/or the rest of the [York Courses website](https://w2prod.sis.yorku.ca/Apps/WebObjects/cdm).  I know that they're planning to replace the entire SIS; but IIRC I read that such a thing will take years to actually happen.

> It was, indeed, 3 hours of work.

I wonder what work is involved which isn't automated.

> I am now employed at York. I'd like to release an official tool with this functionality through proper channels.

Cool!  I wonder which of York's tools or services you spend most of your time on maintaining.
